config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "/users/sign_up", to: redirect("/#modal-new-registration")
  get "/users/sign_in", to: redirect("/#modal-new-session")

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :articles, only: [:show]
  resources :pages, only: [:show]
  resources :materials, only: [:index]
  resources :topics do
    collection {get :user}
    resources :posts
  end
  resources :posts do
    collection {get :user}   
  end
  resources :favorites, only: [:create, :destroy] do
    collection {get :user}
  end

  get "/biblioteka/atsisiusti/:id/:basename.:extension" => "material_attachments#download"

  root 'welcome#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :favoritable, polymorphic: true
  belongs_to :user, inverse_of: :favorites

  validates :user_id, uniqueness: { 
    scope: [:favoritable_id, :favoritable_type],
    message: 'gali mėgti klausimą tik vieną kartą'
  }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_filter :authenticate_user!
  
  def user
    @favorites = current_user.favorites.where(favoritable_type: "Topic")
    @user_favorite_topics = []
    @favorites.each do |f|
      @user_favorite_topics << f.favoritable_type.classify.constantize.find(f.favoritable_id)
    end
  end

  def create
    @favorite = current_user.favorites.build
    params.each do |name, value|
      if name =~ /(.+)_id$/
        @favorite.favoritable_id = value
        @favorite.favoritable_type = $1.capitalize
      end
    end

    respond_to do |format|
      if @favorite.save
        format.html {redirect_to topic_path(Topic.find(@favorite.favoritable_id)), notice: "Klausimas įtrauktas į Jūsų mėgstamiausių sąrašą"}
        format.js { render action: "create_#{@favorite.favoritable_type.downcase}" }
      else
        format.html {redirect_to topic_path(Topic.find(@favorite.favoritable_id)), alert: "Klausimo įtraukti į mėgstamiausių sąrašą nepavyko!"}
        format.js { render action: "create_#{@favorite.favoritable_type.downcase}" }
      end
    end
  end
  
  def destroy
    @favorite = current_user.favorites.find(params[:id])
    @obj = @favorite.favoritable_type.classify.constantize.find(@favorite.favoritable_id)

    respond_to do |format|
      if @favorite.destroy
        format.html {redirect_to topic_path(@topic), notice: "Klausimas pašalintas iš Jūsų mėgstamiausių sąrašo"}
        format.js { render action: "destroy_#{@obj.class.name.downcase}" }
      else
        format.html {redirect_to topic_path(@topic), alert: "Klausimo iš mėgstamiausių sąrašo pašalinti nepavyko!"}
        format.js { render action: "destroy_#{@obj.class.name.downcase}" }
      end
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_post.html.erb
<% if favorite.persisted? %>
  <%= link_to "#{fa_icon 'heart-o'} Patinka!".html_safe, favorite_path(favorite), class: "unlike", id: "favorite-#{favorite.id}", method: :delete, remote: true %>
<% else %>
  <%= link_to "#{fa_icon 'heart-o'} Patinka!".html_safe, favorites_path(post_id: favorite.favoritable_id), class: "like", id: "favoritable-#{favorite.favoritable_id}", method: :post, remote: true %>
<% end %>

app/views/favorites/_favorite_topic.html.erb
<% if favorite.persisted? %>
  <%= link_to "#{fa_icon 'star'}".html_safe, favorite_path(favorite), method: :delete, remote: true %>
<% else %>
  <%= link_to "#{fa_icon 'star-o'}".html_safe, favorites_path(topic_id: favorite.favoritable_id), method: :post, remote: true %>
<% end %>

app/views/favorites/create_post.js.erb
<% if @favorite.errors.any? %>
  $('.navigation .alert ul').html('').append("<% @favorite.errors.full_messages.each do |msg| %><li class='alert-error'><i class='fa fa-exclamation-triangle'></i> <%= msg %></li><% end %>");
<% else %>
  $("#favoritable-<%= @favorite.favoritable_id%>").replaceWith("<%= escape_javascript(render 'favorites/favorite_post', favorite: @favorite) %>");
  var counter = $("#favorite-post-counter-<%= @favorite.favoritable_id%>").text();
  counter++;
  console.log("sukurem ir ikeliam = " + counter)
  $("#favorite-post-counter-<%= @favorite.favoritable_id %>").text(counter);
<% end %>

app/views/favorites/create_topic.js.erb
<% if @favorite.errors.any? %>
  // $('.navigation .alert').remove();
  $('.navigation .alert ul').append("<% @favorite.errors.full_messages.each do |msg| %><li class='alert-error'><i class='fa fa-exclamation-triangle'></i> <%= msg %></li><% end %>");
<% else %>
  $(".favorite-indicator").html("<%= escape_javascript(render 'favorites/favorite_topic', favorite: @favorite) %>");
<% end %>

app/views/favorites/destroy_post.js.erb
<% if @favorite.errors.any? %>
  $('.navigation .alert ul').html("<% @favorite.errors.full_messages.each do |msg| %><li class='alert-error'><i class='fa fa-exclamation-triangle'></i><%= msg %></li><% end %>");
<% else %>
  $("#favorite-<%= @favorite.id%>").replaceWith("<%= escape_javascript(render 'favorites/favorite_post', favorite: current_user.favorites.build(favoritable_id: @obj.id)) %>");
  var counter = $("#favorite-post-counter-<%= @favorite.favoritable_id %>").text();
  counter--;
  $("#favorite-post-counter-<%= @favorite.favoritable_id %>").text(counter);

<% end %>

app/views/favorites/destroy_topic.js.erb
<% if @favorite.errors.any? %>
  $('.navigation .alert ul').html("<% @favorite.errors.full_messages.each do |msg| %><li class='alert-error'><i class='fa fa-exclamation-triangle'></i><%= msg %></li><% end %>");
<% else %>
  if ($(".favorite-indicator").length > 0) {
    $(".favorite-indicator").html("<%= escape_javascript(render 'favorites/favorite_topic', favorite: current_user.favorites.build(favoritable_id: @obj.id)) %>");
  } else if ($('.favorites-user').length > 0) {
    $(".favorite-list #topic-<%= @obj.id %>").remove();
  }
<% end %>

app/views/favorites/user.html.erb
<div id="main-section" class="section">
  <div class="section-heading"><h2>Mano mėgstamiausi</h2></div>
  
  <div class="favorite-list">
    <% @user_favorite_topics.each do |topic| %>

      <div id="topic-<%= topic.id %>" class="topic-item">
        <div class="avatar">
          <%= topic.user.avatar.url.present? ? image_tag(topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
        </div>

        <div class="subject">
          <h2><%= link_to topic.subject, topic %></h2>
          <div class="date">prieš <%= distance_of_time_in_words(topic.updated_at, Time.now) %></div>
        </div>

        <div class="actions">
          <%= link_to "Peržiūrėti", topic, class: "btn btn-green btn-md" %>
          <%= link_to "Ištrinti", favorite_path(@favorites.where(favoritable_id: topic.id, favoritable_type: topic.class.name).first), class: "btn btn-gray btn-md", method: :delete, remote: true %>
        </div>
      </div>

    <% end %>
  </div>
</div>