config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "/users/sign_up", to: redirect("/#modal-new-registration")
  get "/users/sign_in", to: redirect("/#modal-new-session")

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :articles, only: [:show]
  resources :pages, only: [:show]
  resources :materials, only: [:index]
  resources :topics do
    collection {get :user}
    resources :posts
  end
  resources :posts do
    collection {get :user}   
  end
  resources :favorites, only: [:create, :destroy] do
    collection {get :user}
  end

  get "/biblioteka/atsisiusti/:id/:basename.:extension" => "material_attachments#download"

  root 'welcome#index'
end

app/models/topic.rb
require 'friendly_id'

class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts, -> { order "posts.created_at DESC"}, dependent: :destroy
  has_many :favorites, as: :favoritable

  accepts_nested_attributes_for :posts
  
  before_validation :approve_topic
  
  validates :subject, presence: true, length: { maximum: 255 }
  validates :body, presence:true
  validates :user_id, presence: true
  
  scope :visible, -> {where.not(hidden: true)}

  extend FriendlyId
  friendly_id :subject, use: [:slugged, :finders]
  
  class << self
    def by_pinned_or_most_recent_post
      order('topics.pinned DESC').
      order('topics.last_post_at DESC').
      order('topics.id')
    end
  end
  
  private
  
    def approve_topic
      self.approved = true
    end
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :index, :show, :create, :destroy
  before_action :ensure_ownership, only: [:create, :destroy]
  respond_to :html, :js

  def index
    @topics = Topic.visible.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end

  def user
    @topics = current_user.topics.visible.order(created_at: :desc)
  end

  def show
    @post = Post.new
    @topic = Topic.friendly.find(params[:id])
    @posts = @topic.posts
    @favorite = current_user.favorites.find_by(favoritable_id: @topic.id, favoritable_type: @topic.class.name) || current_user.favorites.build(favoritable_id: @topic.id)
    show!
  end

  private

    def ensure_ownership
      if current_user != User.find(topic_params[:user_id] || params[:user_id])
        redirect_to :back, alert: 'Ownership error!'
      end
    end

    def topic_params
      params.fetch(:topic, {}).permit(:user_id, :subject, :body, :locked, :pinned, :hidden, :approved, :views_count)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for((@topic ||= Topic.new), remote: true, format: :js) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Klausimas", class: "form-control" %>
    <%= content_tag :p, @topic.errors[:body].join("<br />").html_safe, class: "input-error" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, placeholder: "Kaulsimo aprašymas", class: "form-control" %>
    <%= content_tag :p, @topic.errors[:body].join("<br />").html_safe, class: "input-error" %>
  </div>

  <div class="actions">
    <%= f.submit "Užduoti klausimą", class: "btn btn-green btn-lg" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic-item">
  <div class="avatar">
    <%= topic.user.avatar.url.present? ? image_tag(topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
    <%= content_tag :div, topic.user.first_name, class: "name" %>
  </div>

  <div class="inner-right">
    <div class="subject">
      <h2><%= link_to topic.subject, topic %></h2>
      <div class="date">prieš <%= distance_of_time_in_words(topic.updated_at, Time.now) %></div>
    </div>

    <div class="body">
      <%= simple_format(topic.body) %>
    </div>
  </div>
</div>

app/views/topics/create.js.erb
<% if @topic.errors.any? %>
  $("form.new_topic").replaceWith("<%= escape_javascript(render 'topics/form', object: @topic) %>");
<% else %>
  $("#main-section .topic-list").prepend("<%= escape_javascript(render 'topics/topic', topic: @topic) %>");
  $("form.new_topic").find("input[type=text], textarea").val("");
<% end %>

app/views/topics/destroy.js.erb
$(".topic-list #topic-<%= @topic.id %>").remove();

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div id="main-section" class="section">
  <div class="section-heading"><h2>Pokalbiai</h2></div>
  
  <div class="inner-top">
    <div class="avatar">
      <%= current_user.avatar.url.present? ? image_tag(current_user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
      <%= content_tag :div, current_user.first_name, class: "name" %>
    </div>
    <%= render 'form' %>
  </div>
  
  <div class="topic-list">
    <% @topics.each do |topic| %>
      <%= render topic %>
    <% end %>

    <div id="infinite-scrolling">
      <%= will_paginate @topics %>
    </div>
  </div>
</div>

app/views/topics/index.js.erb
$('.topic-list #infinite-scrolling').before('<%= j render @topics %>');

<% if @topics.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @topics %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/topics/show.html.erb
<div id="main-section" class="section">
  <div class="section-heading">
    <h2><%= @topic.subject %></h2>

    <div class="favorite-indicator">
      <%= render "favorites/favorite_topic", favorite: @favorite %>
    </div>
    
    <div class="posts-indicator">
      <%= fa_icon 'comment' %>
      <span class="posts-counter"><%= @topic.posts.count %></span>
    </div>
  </div>

  <div class="inner-top">
    <div class="avatar">
      <%= @topic.user.avatar.url.present? ? image_tag(@topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
      <%= content_tag :div, @topic.user.first_name, class: "name" %>
    </div>

    <div class="body">
      <%= simple_format(@topic.body) %>
    </div>

    <div class="actions">
      <a href="#new_post" class="btn btn-green btn-lg">Atsakyti</a>
    </div>
  </div>
  
  <div class="list-heading">Atsakymai</div>

  <div class="post-list">
    <%= render @posts %>
  </div>

  <div class="inner-bottom">
    <div class="avatar">
      <%= current_user.avatar.url.present? ? image_tag(current_user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
      <%= content_tag :div, current_user.first_name, class: "name" %>
    </div>    
    <%= render partial: "posts/form", locals: {topic: @topic, post: @post} %>
  </div>
</div>

app/views/topics/user.html.erb
<div id="main-section" class="section">
  <div class="section-heading"><h2>Mano užduoti klausimai</h2></div>
  
  <div class="topic-list">
    <% @topics.each do |topic| %>

      <div id="topic-<%= topic.id %>" class="topic-item">
        <div class="avatar">
          <%= topic.user.avatar.url.present? ? image_tag(topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
        </div>

        <div class="subject">
          <h2><%= link_to topic.subject, topic %></h2>
          <div class="date">prieš <%= distance_of_time_in_words(topic.updated_at, Time.now) %></div>
        </div>

        <div class="body">
          <%= simple_format(topic.body) %>
        </div>

        <div class="actions">
          <%= link_to "Peržiūrėti", topic, class: "btn btn-primary btn-md" %>
          <%= link_to "Ištrinti", topic_path(topic, user_id: current_user.id), class: "btn btn-gray btn-md", method: :delete, remote: true %>
        </div>
      </div>

    <% end %>
  </div>
</div>