config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "/users/sign_up", to: redirect("/#modal-new-registration")
  get "/users/sign_in", to: redirect("/#modal-new-session")

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :articles, only: [:show]
  resources :pages, only: [:show]
  resources :materials, only: [:index]
  resources :topics do
    collection {get :user}
    resources :posts
  end
  resources :posts do
    collection {get :user}   
  end
  resources :favorites, only: [:create, :destroy] do
    collection {get :user}
  end

  get "/biblioteka/atsisiusti/:id/:basename.:extension" => "material_attachments#download"

  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :favorites, as: :favoritable, dependent: :destroy

  validates_presence_of :user_id, :topic_id, :body

  after_create :set_topic_last_post_at

  mount_uploader :image, ImageUploader

  private

    def set_topic_last_post_at
      topic.update_column(:last_post_at, created_at)
    end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :create, :destroy
  before_action :ensure_ownership, only: [:create, :destroy]
  respond_to :html, :js  

  def user
    @user_posts = current_user.posts
  end

  def create
    @post = Post.new(post_params)
    @topic = Topic.find(params[:topic_id])
    @post.topic_id = @topic.id
    create!
  end

  private

    def ensure_ownership
      if current_user != User.find(post_params[:user_id] || params[:user_id])
        redirect_to :back, alert: 'Ownership error!'
      end
    end

    def post_params
      params.fetch(:post, {}).permit(:user_id, :body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def find_or_build_favorite(post)
    current_user.favorites.find_by(favoritable_id: post.id, favoritable_type: post.class.name) || current_user.favorites.build(favoritable_id: post.id)
  end
end

app/views/posts/_form.html.erb
<%= form_for [@topic, @post], html: { multipart: true }, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.text_area :body, placeholder: "Atsakymas į klausimą", class: "form-control" %>
    <%= content_tag :p, @post.errors[:body].join("<br />").html_safe, class: "input-error" %>
  </div>

  <div class="actions">

    <div class="fileUpload">
      <%= fa_icon "camera" %>
      <%= f.file_field :image, class: "upload", id: "uploadPostImage", accept: 'image/jpeg, image/png, image/gif' %>
    </div>

    <%= link_to "#{fa_icon 'smile-o'}".html_safe, 'javascript:void(0)', class: "smileInsert" %>

    <%= f.submit "Atsakyti", class: "btn btn-green btn-lg", data: { disable_with: "Atsakyti" } %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {

    emojify.setConfig({
      tag_type : 'div'
    });

    $('.post-list .body .text').each(function() {
      var content = $(this).text();
      var replacedContent = emojify.replace(content);
      $(this).html(replacedContent);
    });

    $('body').on('click', '.smileInsert', function(e) {
      e.preventDefault();
    });

    $('textarea').emojiarea({button: '.smileInsert'});

    $.emojiarea.path = '';
    $.emojiarea.icons = {
      ':bowtie:' : '<%= path_to_image("emoji/bowtie.png") %>',
      ':smile:' : '<%= path_to_image("emoji/smile.png") %>',
      ':laughing:' : '<%= path_to_image("emoji/laughing.png") %>',
      ':blush:' : '<%= path_to_image("emoji/blush.png") %>',
      ':smiley:' : '<%= path_to_image("emoji/smiley.png") %>',
      ':relaxed:' : '<%= path_to_image("emoji/relaxed.png") %>',
      ':smirk:' : '<%= path_to_image("emoji/smirk.png") %>',
      ':heart_eyes:' : '<%= path_to_image("emoji/heart_eyes.png") %>',
      ':kissing_heart:' : '<%= path_to_image("emoji/kissing_heart.png") %>',
      ':kissing_closed_eyes:' : '<%= path_to_image("emoji/kissing_closed_eyes.png") %>',
      ':flushed:' : '<%= path_to_image("emoji/flushed.png") %>',
      ':relieved:' : '<%= path_to_image("emoji/relieved.png") %>',
      ':satisfied:' : '<%= path_to_image("emoji/satisfied.png") %>',
      ':grin:' : '<%= path_to_image("emoji/grin.png") %>',
      ':wink:' : '<%= path_to_image("emoji/wink.png") %>',
      ':stuck_out_tongue_winking_eye:' : '<%= path_to_image("emoji/stuck_out_tongue_winking_eye.png") %>',
      ':stuck_out_tongue_closed_eyes:' : '<%= path_to_image("emoji/stuck_out_tongue_closed_eyes.png") %>',
      ':grinning:' : '<%= path_to_image("emoji/grinning.png") %>',
      ':kissing:' : '<%= path_to_image("emoji/kissing.png") %>',
      ':kissing_smiling_eyes:' : '<%= path_to_image("emoji/kissing_smiling_eyes.png") %>',
      ':stuck_out_tongue:' : '<%= path_to_image("emoji/stuck_out_tongue.png") %>',
      ':sleeping:' : '<%= path_to_image("emoji/sleeping.png") %>',
      ':worried:' : '<%= path_to_image("emoji/worried.png") %>',
      ':frowning:' : '<%= path_to_image("emoji/frowning.png") %>',
      ':anguished:' : '<%= path_to_image("emoji/anguished.png") %>',
      ':open_mouth:' : '<%= path_to_image("emoji/open_mouth.png") %>',
      ':grimacing:' : '<%= path_to_image("emoji/grimacing.png") %>',
      ':confused:' : '<%= path_to_image("emoji/confused.png") %>',
      ':hushed:' : '<%= path_to_image("emoji/hushed.png") %>',
      ':expressionless:' : '<%= path_to_image("emoji/expressionless.png") %>',
      ':unamused:' : '<%= path_to_image("emoji/unamused.png") %>',
      ':sweat_smile:' : '<%= path_to_image("emoji/sweat_smile.png") %>',
      ':sweat:' : '<%= path_to_image("emoji/sweat.png") %>',
      ':disappointed_relieved:' : '<%= path_to_image("emoji/disappointed_relieved.png") %>',
      ':weary:' : '<%= path_to_image("emoji/weary.png") %>',
      ':pensive:' : '<%= path_to_image("emoji/pensive.png") %>',
      ':disappointed:' : '<%= path_to_image("emoji/disappointed.png") %>',
      ':confounded:' : '<%= path_to_image("emoji/confounded.png") %>',
      ':fearful:' : '<%= path_to_image("emoji/fearful.png") %>',
      ':cold_sweat:' : '<%= path_to_image("emoji/cold_sweat.png") %>',
      ':persevere:' : '<%= path_to_image("emoji/persevere.png") %>',
      ':cry:' : '<%= path_to_image("emoji/cry.png") %>',
      ':sob:' : '<%= path_to_image("emoji/sob.png") %>',
      ':joy:' : '<%= path_to_image("emoji/joy.png") %>',
      ':astonished:' : '<%= path_to_image("emoji/astonished.png") %>',
      ':scream:' : '<%= path_to_image("emoji/scream.png") %>',
      ':neckbeard:' : '<%= path_to_image("emoji/neckbeard.png") %>',
      ':tired_face:' : '<%= path_to_image("emoji/tired_face.png") %>',
      ':angry:' : '<%= path_to_image("emoji/angry.png") %>',
      ':rage:' : '<%= path_to_image("emoji/rage.png") %>',
      ':triumph:' : '<%= path_to_image("emoji/triumph.png") %>',
      ':sleepy:' : '<%= path_to_image("emoji/sleepy.png") %>',
      ':yum:' : '<%= path_to_image("emoji/yum.png") %>',
      ':mask:' : '<%= path_to_image("emoji/mask.png") %>',
      ':sunglasses:' : '<%= path_to_image("emoji/sunglasses.png") %>',
      ':dizzy_face:' : '<%= path_to_image("emoji/dizzy_face.png") %>',
      ':imp:' : '<%= path_to_image("emoji/imp.png") %>',
      ':smiling_imp:' : '<%= path_to_image("emoji/smiling_imp.png") %>',
      ':neutral_face:' : '<%= path_to_image("emoji/neutral_face.png") %>',
      ':no_mouth:' : '<%= path_to_image("emoji/no_mouth.png") %>',
      ':innocent:' : '<%= path_to_image("emoji/innocent.png") %>'
    };
  });
</script>

app/views/posts/_post.html.erb
<div class="post-item">
  <div class="avatar">
    <%= post.user.avatar.url.present? ? image_tag(post.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
    <%= content_tag :div, current_user.first_name, class: "name" %>
    <%= content_tag :div, "prieš #{distance_of_time_in_words(post.updated_at, Time.now)}", class: "date" %>
  </div>

  <div class="inner-right">
    <div class="body">
      <div class="likes">
        <%= fa_icon "heart" %>
        <%= content_tag :span, post.favorites.count, id: "favorite-post-counter-#{post.id}", class: "counter" %></span>
      </div>
      <%= simple_format(post.body, {class: "text"}, {wrapper_tag: "span"}) %>
    </div>
    <%= content_tag :div, class: "image" do %>
      <%= image_tag post.image.url(:md) %>
    <% end unless post.image.url.blank? %>
    <div class="actions">
      <%= render 'favorites/favorite_post', favorite: find_or_build_favorite(post) %>
    </div>
  </div>
</div>

app/views/posts/_user_post.html.erb
<div id="post-<%= post.id %>" class="post-item">
  <div class="avatar">
    <%= post.topic.user.avatar.url.present? ? image_tag(post.topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
  </div>

  <div class="subject">
    <h2><%= link_to post.topic.subject, post.topic %></h2>
    <div class="date">prieš <%= distance_of_time_in_words(post.topic.updated_at, Time.now) %></div>
  </div>


  <div class="inner-bottom">
    <div class="avatar">
      <%= post.user.avatar.url.present? ? image_tag(post.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
    </div>

    <div class="body">
      <%= simple_format(post.body) %>
    </div>
  </div>

  <div class="actions">
    <%#= link_to "Peržiūrėti", post, class: "btn btn-success btn-md" %>
    <%= link_to "Ištrinti", post_path(post, user_id: current_user.id), class: "btn btn-gray btn-md", method: :delete, remote: true %>
  </div>
</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  $("form.new_post").replaceWith("<%= escape_javascript(render 'posts/form', locals: {topic: @topic, post: @post}) %>");
<% else %>
  var item = $("<%= escape_javascript(render 'posts/post', post: @post) %>");
  var content = item.find('.body .text').first().text();
  var replacedContent = emojify.replace(content);
  item.find('.body .text').html(replacedContent);

  $(".post-list").prepend(item);

  var counter = $('.posts-counter').text();
  counter++;
  $('.posts-counter').text(counter);

  // $("form.new_post").find("input[type=text], textarea").val("");
  $('.emoji-wysiwyg-editor').text('');

  $('html, body').animate({scrollTop: $(".list-heading").offset().top}, 500); 
<% end %>

app/views/posts/destroy.js.erb
$(".post-list #post-<%= @post.id %>").remove();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Topic</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user %></td>
        <td><%= post.topic %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @post.topic %>
</p>

<p>
  <strong>Body:</strong>
  <%= simple_format(@post.body) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/user.html.erb
<div id="main-section" class="section">
  <div class="section-heading"><h2>Mano atsakymai</h2></div>
  
  <div class="post-list">
    <% @user_posts.each do |post| %>
      <%= render "user_post", post: post %>
    <% end %>   
  </div>
</div>