config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "/users/sign_up", to: redirect("/#modal-new-registration")
  get "/users/sign_in", to: redirect("/#modal-new-session")

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :articles, only: [:show]
  resources :pages, only: [:show]
  resources :materials, only: [:index]
  resources :topics do
    collection {get :user}
    resources :posts
  end
  resources :posts do
    collection {get :user}   
  end
  resources :favorites, only: [:create, :destroy] do
    collection {get :user}
  end

  get "/biblioteka/atsisiusti/:id/:basename.:extension" => "material_attachments#download"

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todleris</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <body class="<%= "#{controller_name}-#{action_name}" %> layout-<%= 'application' %>">

    <div id="main">

      <div class="header">
        <div class="container">
          <div class="site-logo">
            <%= link_to(root_path) do %>
              <%= image_tag 'logo.png' %>
            <% end %>
          </div>
          <div class="slogan">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          </div>
          <div class="social-icons">
            <%= link_to 'https://www.facebook.com/Todleris-933345586749287/' do %><%= fa_icon "facebook" %><% end %>
            <%= link_to 'https://www.instagram.com/todleris/' do %><%= fa_icon "instagram" %><% end %>
            <%= link_to 'mailto:info@todleris.lt' do %><%= fa_icon "envelope" %><% end %>
          </div>
        </div>
      </div>

      <div class="navigation">
        <div class="container">
          <nav id="nav-main">
            <ul>
              <% Page.where(menu: true).each do |p| %>
                <%= nav_link p.menu_label, page_path(p) %>
              <% end %>

              <% if user_signed_in? %>
                <li><%= link_to "Baigti darbą", main_app.destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li>
                  <%= link_to "Prisijungti", '#modal-new-session', class: "new-session" %>
                  <%= link_to "Registracija", '#modal-new-registration', class: "new-registration" %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
        <div id="nav-trigger">
            <span>Menu</span>
        </div>
        <nav id="nav-mobile"></nav>

        <div class="alert">
          <ul>
            <% flash.each do |key, value| %>
              <li class="alert-<%= key %>">
                <div class="container">
                  <a href="#" data-dismiss="alert" class="close">×</a>
                  <%= value %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div id="content" class="container">
        <div id="main-content" class="has_rightbar">
          <%= yield %>
        </div>

        <div class="rightbar">
          <% if user_signed_in? %>
            <div class="section section-user">
              <div class="avatar">
                <%= current_user.avatar.url.present? ? image_tag(current_user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
                <%= content_tag :div, current_user.first_name, class: "name" %>
              </div>
  
              <ul class="menu">
                <li class="forums">
                  <%= link_to "#{fa_icon 'comments'} <span>Pokalbiai</span>".html_safe, topics_path %>
                </li>
                <li class="materials">
                  <%= link_to "#{fa_icon 'folder'} <span>Biblioteka</span>".html_safe, materials_path %>
                </li>
                <li class="users">
                  <%= link_to "#{fa_icon 'cog'} <span>Paskyra</span>".html_safe, main_app.edit_user_registration_path %>
                </li>
              </ul>
            </div>
            
            <div class="section section-forum">
              <ul>
                <li>
                  <%= link_to "#{fa_icon 'question'} Mano užduoti klausimai".html_safe, user_topics_path %>
                </li>
                <li>
                  <%= link_to "#{fa_icon 'check'} Mano atsakymai".html_safe, user_posts_path %>
                </li>
                <li>
                  <%= link_to "#{fa_icon 'heart'} Mano mėgstamiausi".html_safe, user_favorites_path %>
                </li>
              </ul>
            </div>

            <div class="section">
              <div class="topic-list">
                <h2>Pokalbiai</h2>
                <% Topic.visible.take(4).each do |topic| %>
                  <div class="topic-item">
                    <%= topic.user.avatar.url.present? ? image_tag(topic.user.avatar.url(:thumb)) : content_tag(:div, nil, class: "image") %>
                    <%= content_tag :div, topic.user.first_name, class: "name" %>
                    <div class="date"> prieš <%= distance_of_time_in_words(topic.updated_at, Time.now) %></div>
                    <div class="subject">
                      <h2><%= link_to topic.subject, topic %></h2>
                    </div>
                    <div class="body">
                      <%= simple_format(truncate topic.body, length: 75) %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="section">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </div>
          <% end %>
        </div>
      </div>

    </div>

    <div id="footer">
      <div class="container">
        <ul>
          <% Page.all.each do |p| %>
            <%= nav_link p.menu_label, page_path(p) %>
          <% end %>
        </ul>
        <div class="copyright"><%= "Visos teisės saugomos &copy; #{Date.current.strftime('%Y')} Todleris".html_safe  %></div>
      </div>
    </div>

    <%= yield(:modals) %>

    <% unless user_signed_in? %>
      <div class="modal multi-step" id="modal-new-registration">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <span class="close"><i class='fa fa-close'></i></span>
            </div>

            <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {:id => "sign_up_user"}, remote: true)  do |f| %>
              <div class="form-alert"><ul></ul></div>

              <%= render "devise/registrations/#{@user.current_step}_step", f: f %>

              <div class="modal-footer">
                <%#= f.submit "Back", :name => "back_button", class: "btn btn-default btn-lg" unless @user.first_step? %>
                <%= f.submit "Kitas žingsnis", class: "btn btn-primary btn-lg" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="modal" id="modal-new-session">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <div class="form-header">Prisijungti</div>
              <span class="close"><i class='fa fa-close'></i></span>
            </div>
            <%= render partial: "devise/sessions/form" %>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>